#!/usr/bin/env bash
rofi \
    -modi "clipboard:$HOME/.config/hypr/scripts/cliphist-rofi-img" \
    -show clipboard \
    -show-icons \
    -kb-delete-entry "D,Shift+Delete" \
    -kb-custom-1 "V" \
    -theme-str 'window { height: 350px; } listview { lines: 4; } element-icon { size: 56px; }'
